import Head from "next/head";
import Table from "../components/table";
import Form from "../components/form";
import { getEmployees, deleteEmployee } from "../library/helper";
import { useState } from "react";
import { useQueryClient } from "react-query";
import { useSelector, useDispatch } from "react-redux";
import { toggleChangeAction, deleteAction } from "../redux/reducer";
import { BiUserPlus, BiX, BiCheck } from "react-icons/bi";

export default function Home() {
  const visible = useSelector((state: any) => state.app.client.toggleForm);
  const dispatch = useDispatch();
  const deleteId = useSelector((state: any) => state.app.client.deleteId);
  const queryClient = useQueryClient();

  const handler = () => {
    dispatch(toggleChangeAction());
  };

  const deleteHandler = async () => {
    if (deleteId) {
      await deleteEmployee(deleteId);
      await queryClient.prefetchQuery("employees", getEmployees);
      await dispatch(deleteAction(null));
    }
  };
  const cancelHandler = async () => {
    console.log("Cancel");
    await dispatch(deleteAction(null));
  };

  return (
    <section>
      <Head>
        <title>CRUD App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800"
              onClick={handler}
            >
              Add Employee{""}
              <span className="px-1">
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
          {deleteId ? DeleteComponent({ deleteHandler, cancelHandler }) : <></>}
        </div>
        {/* COLLAPSABLE FORM */}

        {visible ? <Form /> : <></>}

        {/* TABLE */}
        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </section>
  );
}

function DeleteComponent({ deleteHandler, cancelHandler }: any) {
  return (
    <div className="flex gap-5">
      <p>Are you Sure?</p>
      <button
        className="flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50"
        onClick={deleteHandler}
      >
        YES
        <span className="px-1">
          <BiX color="rgb (255 255 255)" size={25} />
        </span>
      </button>
      <button
        className="flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-green-500 hover:text-gray-50"
        onClick={cancelHandler}
      >
        NO
        <span className="px-1">
          <BiCheck color="rgb (255 255 255)" size={25} />
        </span>
      </button>
    </div>
  );
}
